[package]
name = "hedera-sdk-rust"
version = "0.1.0"
authors = ["LaunchBadge <contact@launchbadge.com>"]
edition = "2018"

[workspace]
members = ["hedera/src/lib.rs", "hedera_crypto/src/lib.rs"]
exclude = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { path = "../hedera_crypto/src" }

[dependencies.ed25519-dalek]
version = "1"

