[package]
name = "hedera_crypto"
version = "0.0.0"
edition = "2018"
authors = ["LaunchBadge <contact@launchbadge.com>"]

[dependencies]
hex = "0.4.3"
ed25519-dalek = "1.0.1"
thiserror = "1.0.24"
rand_core = "0.6.0"
rand = "0.7.0"
